=== STDOUT ===
Set parameter Username
Academic license - for non-commercial use only - expires 2026-09-23
Set parameter TimeLimit to value 300
Gurobi Optimizer version 11.0.0 build v11.0.0rc2 (linux64 - "Ubuntu 22.04.5 LTS")

CPU model: Intel(R) Core(TM) Ultra 7 155H, instruction set [SSE2|AVX|AVX2]
Thread count: 11 physical cores, 22 logical processors, using up to 22 threads

Optimize a model with 1946289 rows, 137774 columns and 5788927 nonzeros
Model fingerprint: 0xb81d9a33
Variable types: 66248 continuous, 71526 integer (71526 binary)
Coefficient statistics:
  Matrix range     [1e+00, 8e+03]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 301942 rows and 15184 columns (presolve time = 5s) ...
Presolve removed 345999 rows and 18453 columns (presolve time = 153s) ...
Presolve removed 345999 rows and 18453 columns (presolve time = 155s) ...
Presolve removed 345999 rows and 18453 columns (presolve time = 160s) ...
Presolve removed 345999 rows and 18453 columns
Presolve time: 301.20s

Explored 0 nodes (0 simplex iterations) in 301.88 seconds (55.47 work units)
Thread count was 1 (of 22 available processors)

Solution count 0

Time limit reached
Best objective -, best bound -, gap -


=== STDERR ===
Traceback (most recent call last):
  File "/home/nischayvagarwal/ugp/github/UGP-Diff-Map-Inference/CARTA/venv/bin/carta", line 8, in <module>
    sys.exit(main_cli())
  File "/home/nischayvagarwal/ugp/github/UGP-Diff-Map-Inference/CARTA/venv/lib/python3.10/site-packages/carta/carta.py", line 176, in main_cli
    main(arguments)
  File "/home/nischayvagarwal/ugp/github/UGP-Diff-Map-Inference/CARTA/venv/lib/python3.10/site-packages/carta/carta.py", line 155, in main
    out = ilp.post_process_solution_from_node_state_labels(solved_model)
  File "/home/nischayvagarwal/ugp/github/UGP-Diff-Map-Inference/CARTA/venv/lib/python3.10/site-packages/carta/ilp.py", line 198, in post_process_solution_from_node_state_labels
    vals[var.varName] = var.x
  File "src/gurobipy/var.pxi", line 125, in gurobipy.Var.__getattr__
  File "src/gurobipy/var.pxi", line 153, in gurobipy.Var.getAttr
  File "src/gurobipy/attrutil.pxi", line 103, in gurobipy._getattr
AttributeError: Unable to retrieve attribute 'x'
